title: gtg7784.blog
logo: https://avatars1.githubusercontent.com/u/32065632?s=460&u=2390d125907246673eb8a2bf9e855dbc14f295e2&v=4
description: https://gtg7784.github.io/
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
